travis:
  secure:
    BINSTAR_TOKEN: flZ6YWURa/4sg5IK97NO9EVkc8RyMK4V/TDmZdN3gvcTaAFEUPw08DM9LJUImgvOSoVwSXIzN0V8OhVkESQPLrCVdTqh9NaIM+niKCSy00wPzlcTvzhcown/BvDa0+YbnwJWHCgfiTfHv5EUXOAue50qHIpfS1GAhewdRmZrVNjTjm/QBU+rkmWpg8pK5Pi43bj0UzTl8AZneDFf1KHk8p5M33nXN8CmDvknOHMT9yS4qdV+UuJl6Q6vzFHbRQshqiqKasM4r7aeEKw8eFT+30JsIOmXLIiCZIIA9x3Fy+cxVv6bcW1XwFUadvm58UO96bcDwwDxPo2hsU6CYERGkP/nf/pKVY2S+ONAb3wKb5LN2qvd3g32hC66l+1kMhJd3UJ5jYPh0FahIL1Jv9yRn8Qy9zR/YeOmnC23UCL1xJhcV3nZ4n2gP7/bUGseG9s0K158kj3g5L/0wksRjNW8Z86Zfu0I2NRwBtyqf6++0lQ9L5mpGxNId2bIBS/0bsnFMaT3c/DvMOwjU4n5PdlhE2h8pG8E8u88Xzh92fs6gXWpIKhtj2iywFhTLWn2HoU4D+wnbPNVfNXBNOU/zS9LLnuyS4Ljh+YR+M9+igWDhMGPhIvSWb+g/L+9BnA1DDZ5WKTJchnWxLIVvlXkUQjGM9oLpaMoKhKoog3O9Lo5bdw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
